# This is a basic workflow to help you get started with Actions
name: Pre-release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre_release:
    name: Pre-release build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: 
        os : [windows-latest, ubuntu-latest, macos-latest]
        include:
          os: windows-latest,
          artifact: "LabTools-Win.7z",
          build_type: "Release",
          cc: "gcc",
          cxx: "g++",
          archiver: "7z a",
        include:
          os: ubuntu-latest,
          artifact: "LabTools-Ubuntu.7z",
          build_type: "Release",
          cc: "gcc",
          cxx: "g++",
          archiver: "7z a",
        include:
          os: macos-latest,
          artifact: "LabTools-MacOS.7z",
          build_type: "Release",
          cc: "clang",
          cxx: "clang++",
          archiver: "7za a",
          
    steps:
      - uses: actions/checkout@v2        
        name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install make cmake
          make --version
          cmake --version

      -name: Configure
        run: |
            mkdir build
            mkdir instdir
            cd build
            cmake \
              -S .. \
              -B . \
              -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            cd ..

      - name: Build
        shell: bash
        run: cmake --build . --config ${{ matrix.config.build_type }}

      - name: Install Strip
        shell: bash
        run: cmake --install . --strip
          
      - name: Pack
        shell: branches
        working-directroy: instdir
        run: |
          ls -laR
          ${{ matrix.config.archiver }} ../${{ matrix.config.artifact}}
          
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "LabTools-alpha"
          files: |
            ${{github.workspace}}/${{ matrix.config.artifact }}
